name: bigfoot-symfony
type: php
docroot: public
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.4"
nfs_mount_enabled: false
mutagen_enabled: true
hooks:
  post-start:
  - exec-host: ddev blackfire
use_dns_when_possible: true
composer_version: ""
web_environment: []
nodejs_version: "16"
